export interface HelpContent {
  purpose: string;
  operations: {
    title: string;
    items: string[];
  };
  shortcuts: {
    title: string;
    items: { key: string; description: string }[];
  };
  tips: string[];
}

export const helpContent: Record<'en' | 'zh', HelpContent> = {
  en: {
    purpose:
      'ASCII Tree Editor is a tool for editing file directory structures generated by the tree command. It provides an intuitive interface to modify, reorganize, and export ASCII tree representations.',
    operations: {
      title: 'How to Use',
      items: [
        'Paste tree command output in the right panel and click "Parse"',
        'The left panel shows an interactive file tree',
        'Click on any item to select it',
        'Hover over items to reveal action buttons',
        'Edit the root directory name at the top',
        'Use expand/collapse button to toggle all directories',
        'Changes are reflected in real-time in the ASCII output',
      ],
    },
    shortcuts: {
      title: 'Keyboard Shortcuts',
      items: [
        { key: 'J / ↓', description: 'Move selected item down' },
        { key: 'K / ↑', description: 'Move selected item up' },
      ],
    },
    tips: [
      'Click on directory items to expand/collapse them',
      'The × button deletes items (including all children for directories)',
      'The + button adds a sibling item below',
      'The ⊕ button adds a child item inside',
      'The ↑↓ buttons move items within the same level',
      'The r button renames the item',
      'Your work is automatically saved to browser storage',
    ],
  },
  zh: {
    purpose:
      'ASCII Tree Editor 是一个用于编辑 tree 命令生成的文件目录结构的工具。它提供了直观的界面来修改、重组和导出 ASCII 树形结构。',
    operations: {
      title: '使用方法',
      items: [
        '在右侧面板粘贴 tree 命令的输出，然后点击"Parse"按钮',
        '左侧面板将显示可交互的文件树',
        '点击任意条目以选中它',
        '鼠标悬停在条目上显示操作按钮',
        '在顶部编辑根目录名称',
        '使用展开/折叠按钮来切换所有目录',
        '修改会实时反映在右侧的 ASCII 输出中',
      ],
    },
    shortcuts: {
      title: '快捷键',
      items: [
        { key: 'J / ↓', description: '将选中项向下移动' },
        { key: 'K / ↑', description: '将选中项向上移动' },
      ],
    },
    tips: [
      '点击目录条目可以展开/折叠',
      '× 按钮删除条目（目录会包含所有子项）',
      '+ 按钮在下方添加同级条目',
      '⊕ 按钮在内部添加子条目',
      '↑↓ 按钮在同级内上下移动条目',
      'r 按钮重命名条目',
      '您的工作会自动保存到浏览器存储中',
    ],
  },
};
