name: Build HTML and Deploy to CF Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        if: github.ref == 'refs/heads/master'
        run: pnpm build

      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: 4.30.0
